config/routes.rb
Rails.application.routes.draw do

  get "sign_up" => "users#new", :as => "sign_up"
  resources :users

  root :to => "photos#index"
  resources :photos
  resources :comments
  resources :sessions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	 before_create :default_status
        belongs_to :article
        belongs_to :user
        validates :content, presence: true, length: { minimum: 10 }

        def default_status
            self.status = "not active"
        end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  scope :status_active, -> {where(status: 'active')}


  validates :title, presence: true,
    length: { minimum: 5 }
  validates :content, presence: true,
    length: { minimum: 10 }
  validates :status, presence: true

  has_many :comments, dependent: :destroy

  has_attached_file :gambar, styles: { medium: "400x200>", thumb: "200x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :gambar, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :gambar, less_than: 200.kilobytes


  self.per_page = 10

  def self.search(search)
      if search
          where(["title LIKE ?","%#{search}%"])
      else
         all
      end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  before_save :add_salt_and_hash

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create,
    length: { minimum: 5 },
    confirmation: true

  def add_salt_and_hash
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  before_create :add_activation_token
    def add_activation_token
        self.activation_token = SecureRandom.urlsafe_base64
        self.activation_status = "not activated"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :check_current_user

  def current_user
    current_user ||= User.where("id = ? and activation_status = ?", session[:user], 'active').first
  end

  def check_current_user
    if current_user.blank?
      flash[:error] = "plase login first before run the action"
      redirect_to new_session_url
    else
      current_user
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]

  def create
    respond_to do |format|
      @comment = Comment.new(params_comment)
      if @comment.save
        format.js {@comments = Article.find_by_id(params[:comment][:article_id]).comments.order("id desc")}
      else
        format.js {@article = Article.find_by_id(params[:comment][:article_id])}
      end
    end
  end

  private
  def params_comment
    params.require(:comment).permit(:article_id, :user_id, :content, :status)
  end
end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]


  def index
    # @photos = Photo.status_active
    # @photos = Photo.paginate(:page => params[:page], per_page: 6)
    # @photos = Photo.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 2, :page => params[:page])
    @photos = Photo.search(params[:search]).paginate(:page => params[:page], per_page: 6)
    @photo = Photo.new
  end

  def home
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find_by_id(params[:id])
  end

  def show
    @photo = Photo.find_by_id(params[:id])
    @comments = @article.comments.order("id desc")
    @comment = Comment.new
  end

  def update
    @photo = Photo.find_by_id(params[:id])
    if @photo.update(params_photo)
      flash[:notice] = "Success Update Records"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'edit'
    end
  end

  def create
    @photo = Photo.new(params_photo)
    if @photo.save
      flash[:notice] = "Success Add Records"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'new'
    end
  end

  def destroy
    @photo = Photo.find_by_id(params[:id])
    if @photo.destroy
      flash[:notice] = "Success Delete a Records"
      redirect_to action: 'index'
    else
      flash[:error] = "fails delete a records"
      redirect_to action: 'index'
    end
  end

  # def import
  #   Photo.import(params[:file])
  #   redirect_to root_url, notice: "Products imported."
  # end

  private
  def params_photo
    params.require(:photo).permit(:title, :content, :status, :gambar)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def edit
    user = User.find_by_activation_token(params[:id])
    if user.try(:update,{activation_token: "", activation_status: "active"})
      flash[:notice] = "Your account has active"
      redirect_to root_url
    else
      flash[:notice] = "Welcome to Rails 4"
      redirect_to root_url
    end
  end

  def new
  end

  def create
    username = params[:username]
    password = params[:password]
    user = User.where("username =? and activation_status =?", username, "active").first
    user_password = BCrypt::Engine.hash_secret(password, user.password_salt) unless user.blank?
    if !user_password.blank? and user.password_hash.eql? user_password
      session[:user] = user.id
      flash[:notice] = "Welcome #{user.username}"
      redirect_to root_url
    else
      params[:username]
      flash[:error] = "Your data not valid"
      render "new"
    end
  end

  def destroy
        session[:user] = nil
        flash[:notice] = "logout session success"
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(params_user)
    if @user.save
      begin
        ConfirmationMailer.confirm_email("#{@user.email}", @user.activation_token).deliver
      rescue
        flash[:notice] = "activation instruction fails send to your email"
      end
      flash[:notice] = "activation instruction has send to #{@user.email}"
      redirect_to photos_path
    else
      flash[:error] = "data not valid"
      render "new"
    end
  end

  private
  def params_user
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper

end

app/views/comments/create.js.erb
<% if @comment.errors.present? %>
        $("#form-comment").html(" <%= j( render 'articles/form' ) %>");
    $($(".field_with_errors")[0]).append("<p class = 'message'> <%= escape_javascript( @comment.errors[:content].first ) %></p>");
        <% else %>
            $("#list-comments").html(" <%= j( render 'articles/comments' ) %>");
            $("#comment_content").val('');
            $("div.field_with_errors p.message").remove();
    <% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#" style="color: floralwhite; font-family:'verdana';"><strong>Bidadari Pagi<span class="glyphicon glyphicon-heart"></span></span></strong></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to '<i class="glyphicon glyphicon-home" style="font-size:28px">                  
                    </i>'.html_safe,  '/' %></li>
      <li ><%= link_to '<i class="glyphicon glyphicon-plus-sign" style="font-size:28px">                  
                    </i>'.html_safe,   '/photos/new' %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
          <h4>
            <% if !current_user %>
              <%= link_to '<i class="glyphicon glyphicon-log-in" style="font-size:28px">                  
                    </i>'.html_safe, new_session_path %>
            <% else %>
              Hello <%= current_user.username %>, 
              <%= link_to '<i class="glyphicon glyphicon-log-out" style="font-size:28px">                  
                    </i>'.html_safe, session_path(current_user.id), method: "DELETE" %>
            <% end %>
          </h4>
      </li>
      <li> <h4>|</h4> </li>
      <li>
        <h4><%= link_to '<i class="glyphicon glyphicon-registration-mark" style="font-size:28px">                  
                    </i>'.html_safe,   '/sign_up' %></h4>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bidadari Pagi</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>	
</head>
<body>

<%= render 'layouts/navbar' %>


<%= yield %>

</body>
</html>

app/views/photos/_comments.html.erb
<% @comments.each do |comment| %>
        <p>
        <b><%= comment.user.try(:username) %></b>
        <br />
        <%= comment.content %>
        </p>
    <% end %>

app/views/photos/_form.html.erb
<%= form_for @comment, url: comments_path, remote: true do |f| %>
        <%= f.hidden_field :article_id, value: @article.id %>
        <% if current_user %>
            <%= f.hidden_field :user_id, value: current_user.id %>
        <% end %>
        <br/>
        <%= f.label :content %>
        <%= f.text_area :content, cols: 20, rows: 10 %>
        <br/>
        <%= f.submit :submit %>
    <% end %>

app/views/photos/edit.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <%= form_for @photo do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <br/>
      <%= f.label :content %>
      <%= f.text_area :content, cols: 20, rows: 10 %>
      <br/>
      <div class="col-md-12" style="padding-bottom: 15px">
        <div class="col-md-3">
          <%= label :photo_status, 'active' %>
        </div>
        <div class="col-md-3">
          <%= f.radio_button :status, "active", class: "radio"%>
        </div>
        <div class="col-md-3">
          <%= label :photo_status, 'off' %>
        </div>
        <div class="col-md-3">
          <%= f.radio_button :status, "off", :checked => true , class: "radio"%>
        </div>
      </div>
      <br/>
      <%= f.file_field :gambar %>
      <%= f.submit :submit, class:"btn btn-primary"%>
    <% end %>
    <div>
      <%= link_to "back to index", photos_path %>
    </div>
  </div>
</div>

app/views/photos/home.html.erb
<% @photos.each do |photo| %>
<h3><%= photo.title %></h3>
<p><%= photo.content.truncate(20)  %></p>
<%= link_to 'read more', photo_path(photo.id) %>

<h4>status : <%= photo.status %></h4>
<hr/>
<% end %>

app/views/photos/index.html.erb
<div class="container">
  <%= form_tag photos_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search]%>
    <%= submit_tag "Search by Title" %>
  <% end %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 ">
      <%= will_paginate @photos, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
  <div class="container">
    <!-- width of .grid-sizer used for columnWidth -->
     <% @photos.each do |photo| %>

      <div class="block text-center">
        
        <%=link_to image_tag(photo.gambar.url(:medium), style: "border-radius: 15px;"), photo.gambar.url(:original), :popup=>['original_image', 'height=auto,width=100%'] %>
        <h3><%= photo.title %></h3>
        <p><%= photo.content %><%#= photo.content.truncate(20)  %></p>
        <%#= link_to 'read more', photo_path(photo.id) %>
        <!-- <h4>status : <%= photo.status %></h4> -->
         <% if (controller_name.eql? 'photos' and (action_name.eql? 'profile')) %>
        <p>
          <span class="glyphicon glyphicon-pencil"><%= link_to '', edit_photo_path(photo.id) %><span>
          <span> | </span>
          <span class="glyphicon glyphicon-trash">
            <%= link_to '', photo_path(photo.id), method: "DELETE", data: {confirm: 'Delete this data ? '} %>
          <span>
        </p>
       <% end %>
      </div>  
    <% end %>
   </div> 
</div>

app/views/photos/new.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <%= form_for @photo, url: photos_path, html: { multipart: true } do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= @photo.errors[:title].first unless @photo.errors[:title].blank? %>
      <br/>
      <%= f.label :content %>
      <%= f.text_area :content, cols: 20, rows: 10 %>
      <%= @photo.errors[:content].first unless @photo.errors[:content].blank? %>
      <br/>
      <%= f.label :status %>
      <div class="col-md-12" style="padding-bottom: 15px">
        <div class="col-md-3">
          <%= label :photo_status, 'active' %>
        </div>
        <div class="col-md-3">
          <%= f.radio_button :status, "active", class: "radio"%>
        </div>
        <div class="col-md-3">
          <%= label :photo_status, 'off' %>
        </div>
        <div class="col-md-3">
          <%= f.radio_button :status, "off", :checked => true , class: "radio"%>
        </div>
      </div>
      <br/>
      <%= f.file_field :gambar %>
      <%= @photo.errors[:gambar].first unless @photo.errors[:gambar].blank? %>
      <%= f.submit :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="grid-item">
  <div class="col-md-6 col-md-offset-3">
    <h3 style="color:  #ffcc00"><%= @photo.title %></h3>
    <p style="color:  #ffcc00"> <%= @photo.content %></p>
    <p style="color:  #ffcc00"> <%= link_to 'back to index', photos_path %></p>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <%= form_for @user do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>
      <%= @user.errors[:username].first unless @user.errors[:username].blank? %>
      <br/>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= @user.errors[:email].first unless @user.errors[:email].blank? %>
      <br/>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= @user.errors[:password].first unless @user.errors[:password].blank? %>
      <br/>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <%= @user.errors[:password_confirmation].first unless @user.errors[:password_confirmation].blank? %>
      <br/>
      <div class="g-recaptcha" data-sitekey="6LfmdRoTAAAAAFJkaQHoZ4If8J756audgGtaVFsr"></div>
    </br>
    <%= recaptcha_tags %>
  </br>
  <%= f.submit :submit, class: "btn btn-primary" %>
<% end %>
</div>
</div>